"""Replace price with rating in Product

Revision ID: 9a874cb4af98
Revises: 
Create Date: 2025-06-21 18:17:59.828231

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a874cb4af98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('games', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('price', sa.INTEGER(), nullable=False))
    op.drop_column('games', 'rating')
    # ### end Alembic commands ###
