name: CI with Docker

on: [push, pull_request]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }} 
  RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }} 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Скачать наш код в виртуальную машину
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp:test .

    # Гоняем наш контейнер и очищаем его
    - name: Run tests inside Docker container
      run: docker run --rm \
  -e SECRET_KEY="$SECRET_KEY" \
  -e RAWG_API_KEY="$RAWG_API_KEY" \
  myapp:test pytest -v --asyncio-mode=auto

